### ISSUE TITLE
Preserve linkImagesToOriginal functionality in the grid

### ISSUE THREAD

**Issue by e0d** [cedricdelpoux/gatsby-remark-images-grid#13]
Any thoughts on the best way to have functionality similar to what is provided by:

https://github.com/Jakst/gatsby-remark-images/blob/master/index.js#L161

That works with the grid?  Happy to hack away at it, but wanted to know if there were thoughts about how to best provide that.

**Comment by cedricdelpoux** [comment]
Fixed in `v1.1.0`
