### ISSUE TITLE
Rendered caption only includes first word of caption

### ISSUE THREAD

**Issue by BruOp** [cedricdelpoux/gatsby-remark-images-grid#4]
Not sure when this started happening, but it looks like the rendered output of this module does not handle the caption properly anymore.

For example, if you have the following in your markdown document:

```grid|2|My super images!
![](../photo1.jpg)
![](../photo2.jpg)
```

The grid will render with the two images, but the caption will only include "My", ignoring everything else.

Poking around, it looks like the full caption is no longer included as part of `node.lang` that's used here: https://github.com/xuopled/gatsby-remark-images-grid/blob/master/src/index.js#L6

Instead, anything after the first space is put into `node.meta`. I've forked this and fixed it by just naively concatenating the two fields, but I'm not sure if you want to investigate something more robust. Might be worth identifying why the behaviour of `node.lang` changed in the first place.

Here's my "hotfix":
https://github.com/BruOp/gatsby-remark-images-grid/commit/517daeefeb083a319755cb30441b07bcb7bf626f

**Comment by cedricdelpoux** [comment]
Hi @BruOp, sorry for the delay. Would you make a PR with your changes?

**Comment by cedricdelpoux** [comment]
Fixed in `v1.1.0`
