### ISSUE TITLE
Code example is wrong

### ISSUE THREAD

**Issue by lorenzvs** [cedricdelpoux/gatsby-remark-images-grid#5]
module.exports = {
    plugins: [
        {
            resolve: "gatsby-transformer-remark",
            options: {
                plugins: [
                    // Make CSS grids available
                    // without options
                    "gatsby-remark-grid"
                    // or
                    // with options
                    {
                        resolve: "gatsby-remark-grid",
                        options: {
                            className: "myCustomClassName",
                            gridGap: "20px",
                            margin: "20px auto",
                        },
                    },
                ],
            },
        },
    ],
}

Should be

module.exports = {
    plugins: [
        {
            resolve: "gatsby-transformer-remark",
            options: {
                plugins: [
                    // Make CSS grids available
                    // without options
                    **"gatsby-remark-images-grid"**
                    // or
                    // with options
                    {
                        resolve: **"gatsby-remark-images-grid"**,
                        options: {
                            className: "myCustomClassName",
                            gridGap: "20px",
                            margin: "20px auto",
                        },
                    },
                ],
            },
        },
    ],
}

**Comment by e0d** [comment]
I agree, will create a PR.

**Comment by e0d** [comment]
A prior PR had fixed one of the instances.  https://github.com/cedricdelpoux/gatsby-remark-images-grid/pull/12/files

**Comment by cedricdelpoux** [comment]
Thank you @e0d for your PR and sorry for the delay! I just merged it
