### ISSUE TITLE
Plugin not working with Amsterdam-theme

### ISSUE THREAD

**Issue by lorenzvs** [cedricdelpoux/gatsby-remark-images-grid#6]
Hi. The plugin doesn't seem to work with [amsterdam-theme](https://www.gatsbyjs.org/packages/gatsby-theme-amsterdam/). It's quite a popular theme so would be nice to figure out why the plugin doesn't trigger the grid after adding the plugin to the gatsby-config and rebuilding. Attached a screenshot of current behaviour.

<img width="878" alt="Screenshot 2020-02-23 at 16 45 03" src="https://user-images.githubusercontent.com/6514303/75115128-2cfd5000-565c-11ea-9dce-df51b520aa35.png">

**Comment by cedricdelpoux** [comment]
Did you put `gatsby-remark-images-grid` first in the list of your `remark` plugins?

**Comment by cedricdelpoux** [comment]
I can't reproduce. Please try to put `gatsby-remark-images-grid` first in the list of your remark plugins.
